name: deeptrace
dependencies:
   - python
   - tensorflow-gpu==2.1.0
   - tensorflow-estimator
   - h5py==2.10.0
   - keras
   - scipy
   - matplotlib
   - jupyter
   - pandas
   - pip
   - pip:
     - tifffile
     - tqdm
     - scikit-image
     - natsort